

//登陆请求
class UserLoginRequestEntity {
    String password;
    String username;

    UserLoginRequestEntity({
        this.password,
        this.username,
    });

    factory UserLoginRequestEntity.fromJson(Map<String, dynamic> json) => UserLoginRequestEntity(
        password: json["password"],
        username: json["username"],
    );

    Map<String, dynamic> toJson() => {
        "password": password,
        "username": username,
    };
}
//登陆返回
class UserLoginResponseEntity {
    String accessToken;
    String displayName;
    List<String> channels;

    UserLoginResponseEntity({
        this.accessToken,
        this.displayName,
        this.channels,
    });

    factory UserLoginResponseEntity.fromJson(Map<String, dynamic> json) => UserLoginResponseEntity(
        accessToken: json["access_token"],
        displayName: json["display_name"],
        channels: List<String>.from(json["channels"].map((x) => x)),
    );

    Map<String, dynamic> toJson() => {
        "access_token": accessToken,
        "display_name": displayName,
        "channels": List<dynamic>.from(channels.map((x) => x)),
    };
}
// Generated by https://quicktype.io

